/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::ArticleComponentOfSection uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ArticleComponentOfSection.
 * 
 * @author 
 */
public class ArticleComponentOfSection extends Article {
	/**
	 * Description of the property simpleSection.
	 */
	public SimpleSection simpleSection = null;
	
	// Start of user code (user defined attributes for ArticleComponentOfSection)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ArticleComponentOfSection() {
		// Start of user code constructor for ArticleComponentOfSection)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ArticleComponentOfSection)
	
	// End of user code
	
	
	/**
	 * Returns simpleSection.
	 * @return simpleSection 
	 */
	public SimpleSection getSimpleSection() {
		return this.simpleSection;
	}
	
	/**
	 * Sets a value to attribute simpleSection. 
	 * @param newSimpleSection 
	 */
	public void setSimpleSection(SimpleSection newSimpleSection) {
		this.simpleSection = newSimpleSection;
	}



}
