/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::ArticleComponentOfChapter uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ArticleComponentOfChapter.
 * 
 * @author 
 */
public class ArticleComponentOfChapter extends Article {
	/**
	 * Description of the property chapterComposedByArticle.
	 */
	public ChapterComposedByArticle chapterComposedByArticle = null;
	
	// Start of user code (user defined attributes for ArticleComponentOfChapter)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ArticleComponentOfChapter() {
		// Start of user code constructor for ArticleComponentOfChapter)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ArticleComponentOfChapter)
	
	// End of user code
	
	
	/**
	 * Returns chapterComposedByArticle.
	 * @return chapterComposedByArticle 
	 */
	public ChapterComposedByArticle getChapterComposedByArticle() {
		return this.chapterComposedByArticle;
	}
	
	/**
	 * Sets a value to attribute chapterComposedByArticle. 
	 * @param newChapterComposedByArticle 
	 */
	public void setChapterComposedByArticle(ChapterComposedByArticle newChapterComposedByArticle) {
		this.chapterComposedByArticle = newChapterComposedByArticle;
	}



}
