/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::Article uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Article.
 * 
 * @author 
 */
public class Article {
	/**
	 * Description of the property number.
	 */
	public int number = 0;
	
	// Start of user code (user defined attributes for Article)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Article() {
		// Start of user code constructor for Article)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Article)
	
	// End of user code
	
	
	/**
	 * Returns number.
	 * @return number 
	 */
	public int getNumber() {
		return this.number;
	}
	
	/**
	 * Sets a value to attribute number. 
	 * @param newNumber 
	 */
	public void setNumber(int newNumber) {
		this.number = newNumber;
	}



}
