/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::Book uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:50 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Book.
 * 
 * @author 
 */
public class Book {
	/**
	 * Description of the property romanNumber.
	 */
	public int romanNumber = 0;
	
	// Start of user code (user defined attributes for Book)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Book() {
		// Start of user code constructor for Book)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Book)
	
	// End of user code
	
	
	/**
	 * Returns romanNumber.
	 * @return romanNumber 
	 */
	public int getRomanNumber() {
		return this.romanNumber;
	}
	
	/**
	 * Sets a value to attribute romanNumber. 
	 * @param newRomanNumber 
	 */
	public void setRomanNumber(int newRomanNumber) {
		this.romanNumber = newRomanNumber;
	}



}
