/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::Caput uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Caput.
 * 
 * @author 
 */
public class Caput {
	/**
	 * Description of the property text.
	 */
	public String text = "";
	
	/**
	 * Description of the property composedArticle.
	 */
	public ComposedArticle composedArticle = null;
	
	// Start of user code (user defined attributes for Caput)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Caput() {
		// Start of user code constructor for Caput)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Caput)
	
	// End of user code
	
	
	/**
	 * Returns text.
	 * @return text 
	 */
	public String getText() {
		return this.text;
	}
	
	/**
	 * Sets a value to attribute text. 
	 * @param newText 
	 */
	public void setText(String newText) {
		this.text = newText;
	}

	/**
	 * Returns composedArticle.
	 * @return composedArticle 
	 */
	public ComposedArticle getComposedArticle() {
		return this.composedArticle;
	}
	
	/**
	 * Sets a value to attribute composedArticle. 
	 * @param newComposedArticle 
	 */
	public void setComposedArticle(ComposedArticle newComposedArticle) {
		this.composedArticle = newComposedArticle;
	}



}
