/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::ComponentChapter uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:50 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ComponentChapter.
 * 
 * @author 
 */
public class ComponentChapter extends Chapter {
	// Start of user code (user defined attributes for ComponentChapter)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ComponentChapter() {
		// Start of user code constructor for ComponentChapter)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ComponentChapter)
	
	// End of user code
	
	


}
