/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::ComposedArticle uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ComposedArticle.
 * 
 * @author 
 */
public class ComposedArticle extends Article {
	/**
	 * Description of the property caput.
	 */
	public Caput caput = null;
	
	// Start of user code (user defined attributes for ComposedArticle)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ComposedArticle() {
		// Start of user code constructor for ComposedArticle)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ComposedArticle)
	
	// End of user code
	
	
	/**
	 * Returns caput.
	 * @return caput 
	 */
	public Caput getCaput() {
		return this.caput;
	}
	
	/**
	 * Sets a value to attribute caput. 
	 * @param newCaput 
	 */
	public void setCaput(Caput newCaput) {
		this.caput = newCaput;
	}



}
