/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::ComponentCharter uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:50 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ComponentCharter.
 * 
 * @author 
 */
public class ComponentCharter extends Charter {
	// Start of user code (user defined attributes for ComponentCharter)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ComponentCharter() {
		// Start of user code constructor for ComponentCharter)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ComponentCharter)
	
	// End of user code
	
	


}
