/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::GeneralPart uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of GeneralPart.
 * 
 * @author 
 */
public class GeneralPart extends DoublePart {
	// Start of user code (user defined attributes for GeneralPart)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public GeneralPart() {
		// Start of user code constructor for GeneralPart)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for GeneralPart)
	
	// End of user code
	
	


}
