/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::ItemComponentOfArticle uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:50 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ItemComponentOfArticle.
 * 
 * @author 
 */
public class ItemComponentOfArticle extends Item {
	/**
	 * Description of the property articleComposedOfItem.
	 */
	public ArticleComposedOfItem articleComposedOfItem = null;
	
	// Start of user code (user defined attributes for ItemComponentOfArticle)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ItemComponentOfArticle() {
		// Start of user code constructor for ItemComponentOfArticle)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ItemComponentOfArticle)
	
	// End of user code
	
	
	/**
	 * Returns articleComposedOfItem.
	 * @return articleComposedOfItem 
	 */
	public ArticleComposedOfItem getArticleComposedOfItem() {
		return this.articleComposedOfItem;
	}
	
	/**
	 * Sets a value to attribute articleComposedOfItem. 
	 * @param newArticleComposedOfItem 
	 */
	public void setArticleComposedOfItem(ArticleComposedOfItem newArticleComposedOfItem) {
		this.articleComposedOfItem = newArticleComposedOfItem;
	}



}
