/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::Letter uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Letter.
 * 
 * @author 
 */
public class Letter {
	/**
	 * Description of the property composedItem.
	 */
	public ComposedItem composedItem = null;
	
	/**
	 * Description of the property letter.
	 */
	public char letter = 0;
	
	// Start of user code (user defined attributes for Letter)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Letter() {
		// Start of user code constructor for Letter)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Letter)
	
	// End of user code
	
	
	/**
	 * Returns composedItem.
	 * @return composedItem 
	 */
	public ComposedItem getComposedItem() {
		return this.composedItem;
	}
	
	/**
	 * Sets a value to attribute composedItem. 
	 * @param newComposedItem 
	 */
	public void setComposedItem(ComposedItem newComposedItem) {
		this.composedItem = newComposedItem;
	}

	/**
	 * Returns letter.
	 * @return letter 
	 */
	public char getLetter() {
		return this.letter;
	}
	
	/**
	 * Sets a value to attribute letter. 
	 * @param newLetter 
	 */
	public void setLetter(char newLetter) {
		this.letter = newLetter;
	}



}
