/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::LetterDiscriminator uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of LetterDiscriminator.
 * 
 * @author 
 */
public class LetterDiscriminator {
	/**
	 * Description of the property composedLetter.
	 */
	public ComposedLetter composedLetter = null;
	
	/**
	 * Description of the property cardinalNumber.
	 */
	public int cardinalNumber = 0;
	
	// Start of user code (user defined attributes for LetterDiscriminator)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public LetterDiscriminator() {
		// Start of user code constructor for LetterDiscriminator)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for LetterDiscriminator)
	
	// End of user code
	
	
	/**
	 * Returns composedLetter.
	 * @return composedLetter 
	 */
	public ComposedLetter getComposedLetter() {
		return this.composedLetter;
	}
	
	/**
	 * Sets a value to attribute composedLetter. 
	 * @param newComposedLetter 
	 */
	public void setComposedLetter(ComposedLetter newComposedLetter) {
		this.composedLetter = newComposedLetter;
	}

	/**
	 * Returns cardinalNumber.
	 * @return cardinalNumber 
	 */
	public int getCardinalNumber() {
		return this.cardinalNumber;
	}
	
	/**
	 * Sets a value to attribute cardinalNumber. 
	 * @param newCardinalNumber 
	 */
	public void setCardinalNumber(int newCardinalNumber) {
		this.cardinalNumber = newCardinalNumber;
	}



}
