/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::OrdinaryArticle uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of OrdinaryArticle.
 * 
 * @author 
 */
public class OrdinaryArticle extends Article {
	/**
	 * Description of the property normativeAct.
	 */
	public NormativeAct normativeAct = null;
	
	// Start of user code (user defined attributes for OrdinaryArticle)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public OrdinaryArticle() {
		// Start of user code constructor for OrdinaryArticle)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for OrdinaryArticle)
	
	// End of user code
	
	
	/**
	 * Returns normativeAct.
	 * @return normativeAct 
	 */
	public NormativeAct getNormativeAct() {
		return this.normativeAct;
	}
	
	/**
	 * Sets a value to attribute normativeAct. 
	 * @param newNormativeAct 
	 */
	public void setNormativeAct(NormativeAct newNormativeAct) {
		this.normativeAct = newNormativeAct;
	}



}
