/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::Paragraph uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Paragraph.
 * 
 * @author 
 */
public class Paragraph {
	/**
	 * Description of the property identification.
	 */
	public String identification = "";
	
	/**
	 * Description of the property articleComposedOfParagraph.
	 */
	public ArticleComposedOfParagraph articleComposedOfParagraph = null;
	
	// Start of user code (user defined attributes for Paragraph)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Paragraph() {
		// Start of user code constructor for Paragraph)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Paragraph)
	
	// End of user code
	
	
	/**
	 * Returns identification.
	 * @return identification 
	 */
	public String getIdentification() {
		return this.identification;
	}
	
	/**
	 * Sets a value to attribute identification. 
	 * @param newIdentification 
	 */
	public void setIdentification(String newIdentification) {
		this.identification = newIdentification;
	}

	/**
	 * Returns articleComposedOfParagraph.
	 * @return articleComposedOfParagraph 
	 */
	public ArticleComposedOfParagraph getArticleComposedOfParagraph() {
		return this.articleComposedOfParagraph;
	}
	
	/**
	 * Sets a value to attribute articleComposedOfParagraph. 
	 * @param newArticleComposedOfParagraph 
	 */
	public void setArticleComposedOfParagraph(ArticleComposedOfParagraph newArticleComposedOfParagraph) {
		this.articleComposedOfParagraph = newArticleComposedOfParagraph;
	}



}
