/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::Preamble uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Preamble.
 * 
 * @author 
 */
public class Preamble {
	/**
	 * Description of the property normativeAct.
	 */
	public NormativeAct normativeAct = null;
	
	/**
	 * Description of the property text.
	 */
	public String text = "";
	
	// Start of user code (user defined attributes for Preamble)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Preamble() {
		// Start of user code constructor for Preamble)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Preamble)
	
	// End of user code
	
	
	/**
	 * Returns normativeAct.
	 * @return normativeAct 
	 */
	public NormativeAct getNormativeAct() {
		return this.normativeAct;
	}
	
	/**
	 * Sets a value to attribute normativeAct. 
	 * @param newNormativeAct 
	 */
	public void setNormativeAct(NormativeAct newNormativeAct) {
		this.normativeAct = newNormativeAct;
	}

	/**
	 * Returns text.
	 * @return text 
	 */
	public String getText() {
		return this.text;
	}
	
	/**
	 * Sets a value to attribute text. 
	 * @param newText 
	 */
	public void setText(String newText) {
		this.text = newText;
	}



}
