/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::Section uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Section.
 * 
 * @author 
 */
public class Section {
	/**
	 * Description of the property romanNumber.
	 */
	public int romanNumber = 0;
	
	// Start of user code (user defined attributes for Section)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Section() {
		// Start of user code constructor for Section)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Section)
	
	// End of user code
	
	
	/**
	 * Returns romanNumber.
	 * @return romanNumber 
	 */
	public int getRomanNumber() {
		return this.romanNumber;
	}
	
	/**
	 * Sets a value to attribute romanNumber. 
	 * @param newRomanNumber 
	 */
	public void setRomanNumber(int newRomanNumber) {
		this.romanNumber = newRomanNumber;
	}



}
