/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::SimpleArticle uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of SimpleArticle.
 * 
 * @author 
 */
public class SimpleArticle extends Article {
	/**
	 * Description of the property text.
	 */
	public String text = "";
	
	// Start of user code (user defined attributes for SimpleArticle)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public SimpleArticle() {
		// Start of user code constructor for SimpleArticle)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for SimpleArticle)
	
	// End of user code
	
	
	/**
	 * Returns text.
	 * @return text 
	 */
	public String getText() {
		return this.text;
	}
	
	/**
	 * Sets a value to attribute text. 
	 * @param newText 
	 */
	public void setText(String newText) {
		this.text = newText;
	}



}
