/*******************************************************************************
 * File generated from the Normative Acts::barcelos2013normativeacts::model::normative_acts::normative_acts::Subsection uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:49 CEST
 *******************************************************************************/
package barcelos2013normativeacts.model.normative_acts.normative_acts;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Subsection.
 * 
 * @author 
 */
public class Subsection extends SimpleSection {
	// Start of user code (user defined attributes for Subsection)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Subsection() {
		// Start of user code constructor for Subsection)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Subsection)
	
	// End of user code
	
	


}
