/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::Access uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Access.
 * 
 * @author 
 */
public class Access {
	/**
	 * Description of the property accessedAccount.
	 */
	public final AccessedAccount accessedAccount = null;
	
	/**
	 * Description of the property accessingDevice.
	 */
	public final AccessingDevice accessingDevice = null;
	
	// Start of user code (user defined attributes for Access)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Access() {
		// Start of user code constructor for Access)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Access)
	
	// End of user code
	
	
	/**
	 * Returns accessedAccount.
	 * @return accessedAccount 
	 */
	public AccessedAccount getAccessedAccount() {
		return this.accessedAccount;
	}

	/**
	 * Returns accessingDevice.
	 * @return accessingDevice 
	 */
	public AccessingDevice getAccessingDevice() {
		return this.accessingDevice;
	}



}
