/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::Account uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Account.
 * 
 * @author 
 */
public class Account {
	/**
	 * Description of the property holder.
	 */
	public final Client holder = null;
	
	/**
	 * Description of the property bank.
	 */
	public final Bank bank = null;
	
	// Start of user code (user defined attributes for Account)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Account() {
		// Start of user code constructor for Account)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Account)
	
	// End of user code
	
	
	/**
	 * Returns holder.
	 * @return holder 
	 */
	public Client getHolder() {
		return this.holder;
	}

	/**
	 * Returns bank.
	 * @return bank 
	 */
	public Bank getBank() {
		return this.bank;
	}



}
