/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::ATM uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ATM.
 * 
 * @author 
 */
public class ATM extends Device {
	/**
	 * Description of the property withdrawingATMRole.
	 */
	public WithdrawingATM withdrawingATMRole = null;
	
	// Start of user code (user defined attributes for ATM)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ATM() {
		// Start of user code constructor for ATM)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ATM)
	
	// End of user code
	
	
	/**
	 * Returns withdrawingATMRole.
	 * @return withdrawingATMRole 
	 */
	public WithdrawingATM getWithdrawingATMRole() {
		return this.withdrawingATMRole;
	}
	
	/**
	 * Sets a value to attribute withdrawingATMRole. 
	 * @param newWithdrawingATMRole 
	 */
	public void setWithdrawingATMRole(WithdrawingATM newWithdrawingATMRole) {
		this.withdrawingATMRole = newWithdrawingATMRole;
	}



}
