/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::Client uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Client.
 * 
 * @author 
 */
public interface Client {


	/**
	 * Returns account.
	 * @return account 
	 */
	ArrayList<Account> getAccount();
	
	
	/**
	 * Sets a value to attribute account. 
	 * @param newAccount 
	 */
	void setAccount(ArrayList<Account> newAccount);


	// Start of user code (user defined methods for Client)
	
	// End of user code


}
