/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::Device uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Device.
 * 
 * @author 
 */
public class Device implements SpatialEntity {
	/**
	 * Description of the property accessingDeviceRole.
	 */
	public AccessingDevice accessingDeviceRole = null;
	
	// Start of user code (user defined attributes for Device)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Device() {
		// Start of user code constructor for Device)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Device)
	
	// End of user code
	/**
	 * Returns location.
	 * Originates from implemented interface.
	 * @return location 
	 */
	@Override
	public Location getLocation() {
		// Start of user code for method getLocation
		// TODO implement
		return null;
		// End of user code
	}
	
	/**
	 * Sets a value to attribute location. 
	 * Originates from implemented interface.
	 * @param newLocation 
	 */
	@Override
	public void setLocation(Location newLocation) {
		// Start of user code for method setLocation
		// TODO implement
		// End of user code
	}
	
	
	/**
	 * Returns accessingDeviceRole.
	 * @return accessingDeviceRole 
	 */
	public AccessingDevice getAccessingDeviceRole() {
		return this.accessingDeviceRole;
	}
	
	/**
	 * Sets a value to attribute accessingDeviceRole. 
	 * @param newAccessingDeviceRole 
	 */
	public void setAccessingDeviceRole(AccessingDevice newAccessingDeviceRole) {
		this.accessingDeviceRole = newAccessingDeviceRole;
	}



}
