/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::InactiveAccount uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of InactiveAccount.
 * 
 * @author 
 */
public class InactiveAccount {
	// Start of user code (user defined attributes for InactiveAccount)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public InactiveAccount() {
		// Start of user code constructor for InactiveAccount)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for InactiveAccount)
	
	// End of user code
	
	


}
