/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::Location uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Location.
 * 
 * @author 
 */
public class Location {
	/**
	 * Description of the property spatialEntity.
	 */
	public final SpatialEntity spatialEntity = null;
	
	// Start of user code (user defined attributes for Location)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Location() {
		// Start of user code constructor for Location)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Location)
	
	// End of user code
	
	
	/**
	 * Returns spatialEntity.
	 * @return spatialEntity 
	 */
	public SpatialEntity getSpatialEntity() {
		return this.spatialEntity;
	}



}
