/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::Mobile uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Mobile.
 * 
 * @author 
 */
public class Mobile extends Device {
	// Start of user code (user defined attributes for Mobile)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Mobile() {
		// Start of user code constructor for Mobile)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Mobile)
	
	// End of user code
	
	


}
