/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::OrganizationMember uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of OrganizationMember.
 * 
 * @author 
 */
public class OrganizationMember extends Organization {
	/**
	 * Description of the property groupOfOrganizations.
	 */
	public GroupOfOrganizations groupOfOrganizations = null;
	
	// Start of user code (user defined attributes for OrganizationMember)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public OrganizationMember() {
		// Start of user code constructor for OrganizationMember)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for OrganizationMember)
	
	// End of user code
	
	
	/**
	 * Returns groupOfOrganizations.
	 * @return groupOfOrganizations 
	 */
	public GroupOfOrganizations getGroupOfOrganizations() {
		return this.groupOfOrganizations;
	}
	
	/**
	 * Sets a value to attribute groupOfOrganizations. 
	 * @param newGroupOfOrganizations 
	 */
	public void setGroupOfOrganizations(GroupOfOrganizations newGroupOfOrganizations) {
		this.groupOfOrganizations = newGroupOfOrganizations;
	}



}
