/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::Organization uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Organization.
 * 
 * @author 
 */
public class Organization {
	/**
	 * Description of the property clientOrganizationRole.
	 */
	public ClientOrganization clientOrganizationRole = null;
	
	// Start of user code (user defined attributes for Organization)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Organization() {
		// Start of user code constructor for Organization)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Organization)
	
	// End of user code
	
	
	/**
	 * Returns clientOrganizationRole.
	 * @return clientOrganizationRole 
	 */
	public ClientOrganization getClientOrganizationRole() {
		return this.clientOrganizationRole;
	}
	
	/**
	 * Sets a value to attribute clientOrganizationRole. 
	 * @param newClientOrganizationRole 
	 */
	public void setClientOrganizationRole(ClientOrganization newClientOrganizationRole) {
		this.clientOrganizationRole = newClientOrganizationRole;
	}



}
