/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::Person uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Person.
 * 
 * @author 
 */
public class Person {
	/**
	 * Description of the property clientPersonRole.
	 */
	public ClientPerson clientPersonRole = null;
	
	// Start of user code (user defined attributes for Person)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Person() {
		// Start of user code constructor for Person)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Person)
	
	// End of user code
	
	
	/**
	 * Returns clientPersonRole.
	 * @return clientPersonRole 
	 */
	public ClientPerson getClientPersonRole() {
		return this.clientPersonRole;
	}
	
	/**
	 * Sets a value to attribute clientPersonRole. 
	 * @param newClientPersonRole 
	 */
	public void setClientPersonRole(ClientPerson newClientPersonRole) {
		this.clientPersonRole = newClientPersonRole;
	}



}
