/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::SpatialEntity uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of SpatialEntity.
 * 
 * @author 
 */
public interface SpatialEntity {


	/**
	 * Returns location.
	 * @return location 
	 */
	Location getLocation();
	
	
	/**
	 * Sets a value to attribute location. 
	 * @param newLocation 
	 */
	void setLocation(Location newLocation);


	// Start of user code (user defined methods for SpatialEntity)
	
	// End of user code


}
