/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::Withdraw uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Withdraw.
 * 
 * @author 
 */
public class Withdraw {
	/**
	 * Description of the property withdrawedAccount.
	 */
	public final WithdrawedAccount withdrawedAccount = null;
	
	/**
	 * Description of the property withdrawingATM.
	 */
	public final WithdrawingATM withdrawingATM = null;
	
	// Start of user code (user defined attributes for Withdraw)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Withdraw() {
		// Start of user code constructor for Withdraw)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Withdraw)
	
	// End of user code
	
	
	/**
	 * Returns withdrawedAccount.
	 * @return withdrawedAccount 
	 */
	public WithdrawedAccount getWithdrawedAccount() {
		return this.withdrawedAccount;
	}

	/**
	 * Returns withdrawingATM.
	 * @return withdrawingATM 
	 */
	public WithdrawingATM getWithdrawingATM() {
		return this.withdrawingATM;
	}



}
