/*******************************************************************************
 * File generated from the Banking::bankmodel::model::banking::model::WithdrawingATM uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:29 CEST
 *******************************************************************************/
package bankmodel.model.banking.model;

import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of WithdrawingATM.
 * 
 * @author 
 */
public class WithdrawingATM {
	/**
	 * Description of the property withdraw.
	 */
	public ArrayList<Withdraw> withdraw = new ArrayList<Withdraw>();
	
	/**
	 * Description of the property aTM.
	 */
	public final ATM aTM = null;
	
	// Start of user code (user defined attributes for WithdrawingATM)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public WithdrawingATM() {
		// Start of user code constructor for WithdrawingATM)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for WithdrawingATM)
	
	// End of user code
	
	
	/**
	 * Returns withdraw.
	 * @return withdraw 
	 */
	public ArrayList<Withdraw> getWithdraw() {
		return this.withdraw;
	}
	
	/**
	 * Sets a value to attribute withdraw. 
	 * @param newWithdraw 
	 */
	public void setWithdraw(ArrayList<Withdraw> newWithdraw) {
	    this.withdraw = newWithdraw;
	}
	
	/**
	 * Adds one attribute (if withdraw had a multiple cardinality)
	 * @param withdrawToAdd in withdraw
	 */
	public void addWithdrawToWithdraw(Withdraw withdrawToAdd) {
		this.withdraw.add(withdrawToAdd);
	}
	
	/**
	 * Removes an attribute (if withdraw had a multiple cardinality)
	 * @param withdrawToRemove in withdraw
	 */
	public void removeWithdrawToWithdraw(Withdraw withdrawToRemove) {
		this.withdraw.remove(withdrawToRemove);
	}
	
	/**
	 * Adds all the attribute (if withdraw had a multiple cardinality)
	 * @param withdrawsToAdd in withdraw
	 */
	public void addAllWithdrawToWithdraw(ArrayList<Withdraw> withdrawsToAdd) {
		this.withdraw.addAll(withdrawsToAdd);
	}
	
	/**
	 * Removes all the attribute (if withdraw had a multiple cardinality)
	 * @param withdrawsToRemove in withdraw
	 */
	public void removeAllWithdrawToWithdraw(ArrayList<Withdraw> withdrawsToRemove) {
		this.withdraw.removeAll(withdrawsToRemove);
	}

	/**
	 * Returns aTM.
	 * @return aTM 
	 */
	public ATM getATM() {
		return this.aTM;
	}



}
