/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::dbso::DataSchema uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:43 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.dbso;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of DataSchema.
 * 
 * @author 
 */
public class DataSchema extends Schema {
	/**
	 * Description of the property informationSchema.
	 */
	public InformationSchema informationSchema = null;
	
	// Start of user code (user defined attributes for DataSchema)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public DataSchema() {
		// Start of user code constructor for DataSchema)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for DataSchema)
	
	// End of user code
	
	
	/**
	 * Returns informationSchema.
	 * @return informationSchema 
	 */
	public InformationSchema getInformationSchema() {
		return this.informationSchema;
	}
	
	/**
	 * Sets a value to attribute informationSchema. 
	 * @param newInformationSchema 
	 */
	public void setInformationSchema(InformationSchema newInformationSchema) {
		this.informationSchema = newInformationSchema;
	}



}
