/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::dbso::DBMSItem uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:43 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.dbso;

import aguiar2018rdbso.model.ontology.spo.SoftwareItem;
import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of DBMSItem.
 * 
 * @author 
 */
public interface DBMSItem  extends SoftwareItem{


	/**
	 * Returns databaseSystem.
	 * @return databaseSystem 
	 */
	DatabaseSystem getDatabaseSystem();
	
	
	/**
	 * Sets a value to attribute databaseSystem. 
	 * @param newDatabaseSystem 
	 */
	void setDatabaseSystem(DatabaseSystem newDatabaseSystem);

	/**
	 * Returns loadedDBMSCopy.
	 * @return loadedDBMSCopy 
	 */
	ArrayList<LoadedDBMSCopy> getLoadedDBMSCopy();
	
	
	/**
	 * Sets a value to attribute loadedDBMSCopy. 
	 * @param newLoadedDBMSCopy 
	 */
	void setLoadedDBMSCopy(ArrayList<LoadedDBMSCopy> newLoadedDBMSCopy);


	// Start of user code (user defined methods for DBMSItem)
	
	// End of user code


}
