/*******************************************************************************
 * File generated from the Project Management Ontology::projectmanagementontology::model::project_management_ontology::project_management_ontology::ActivityPhase uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 31 October 2024 16:51:36 CET
 *******************************************************************************/
package projectmanagementontology.model.project_management_ontology.project_management_ontology;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ActivityPhase.
 * 
 * @author 
 */
public interface ActivityPhase {


	/**
	 * Returns activity.
	 * @return activity 
	 */
	Activity getActivity();


	// Start of user code (user defined methods for ActivityPhase)
	
	// End of user code


}
