/*******************************************************************************
 * File generated from the Project Management Ontology::projectmanagementontology::model::project_management_ontology::project_management_ontology::Activity uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 31 October 2024 16:51:36 CET
 *******************************************************************************/
package projectmanagementontology.model.project_management_ontology.project_management_ontology;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Activity.
 * 
 * @author 
 */
public class Activity {
	/**
	 * Description of the property phase.
	 */
	public ActivityPhase phase = null;
	
	// Start of user code (user defined attributes for Activity)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Activity() {
		// Start of user code constructor for Activity)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Activity)
	
	// End of user code
	
	
	/**
	 * Returns phase.
	 * @return phase 
	 */
	public ActivityPhase getPhase() {
		return this.phase;
	}
	
	/**
	 * Sets a value to attribute phase. 
	 * @param newPhase 
	 */
	public void setPhase(ActivityPhase newPhase) {
		this.phase = newPhase;
	}



}
