/*******************************************************************************
 * File generated from the Project Management Ontology::projectmanagementontology::model::project_management_ontology::project_management_ontology::Atomic uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 31 October 2024 16:51:36 CET
 *******************************************************************************/
package projectmanagementontology.model.project_management_ontology.project_management_ontology;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Atomic.
 * 
 * @author 
 */
public class Atomic extends Activity {
	/**
	 * Description of the property composed.
	 */
	public Composed composed = null;
	
	// Start of user code (user defined attributes for Atomic)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Atomic() {
		// Start of user code constructor for Atomic)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Atomic)
	
	// End of user code
	
	
	/**
	 * Returns composed.
	 * @return composed 
	 */
	public Composed getComposed() {
		return this.composed;
	}
	
	/**
	 * Sets a value to attribute composed. 
	 * @param newComposed 
	 */
	public void setComposed(Composed newComposed) {
		this.composed = newComposed;
	}



}
