/*******************************************************************************
 * File generated from the Project Management Ontology::projectmanagementontology::model::project_management_ontology::project_management_ontology::Money uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 31 October 2024 16:51:36 CET
 *******************************************************************************/
package projectmanagementontology.model.project_management_ontology.project_management_ontology;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Money.
 * 
 * @author 
 */
public class Money {
	/**
	 * Description of the property financialResourceRole.
	 */
	public FinancialResource financialResourceRole = null;
	
	// Start of user code (user defined attributes for Money)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Money() {
		// Start of user code constructor for Money)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Money)
	
	// End of user code
	
	
	/**
	 * Returns financialResourceRole.
	 * @return financialResourceRole 
	 */
	public FinancialResource getFinancialResourceRole() {
		return this.financialResourceRole;
	}
	
	/**
	 * Sets a value to attribute financialResourceRole. 
	 * @param newFinancialResourceRole 
	 */
	public void setFinancialResourceRole(FinancialResource newFinancialResourceRole) {
		this.financialResourceRole = newFinancialResourceRole;
	}



}
