/*******************************************************************************
 * File generated from the Project Management Ontology::projectmanagementontology::model::project_management_ontology::project_management_ontology::Person uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 31 October 2024 16:51:36 CET
 *******************************************************************************/
package projectmanagementontology.model.project_management_ontology.project_management_ontology;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Person.
 * 
 * @author 
 */
public class Person {
	/**
	 * Description of the property humanResourceRole.
	 */
	public HumanResource humanResourceRole = null;
	
	// Start of user code (user defined attributes for Person)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Person() {
		// Start of user code constructor for Person)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Person)
	
	// End of user code
	
	
	/**
	 * Returns humanResourceRole.
	 * @return humanResourceRole 
	 */
	public HumanResource getHumanResourceRole() {
		return this.humanResourceRole;
	}
	
	/**
	 * Sets a value to attribute humanResourceRole. 
	 * @param newHumanResourceRole 
	 */
	public void setHumanResourceRole(HumanResource newHumanResourceRole) {
		this.humanResourceRole = newHumanResourceRole;
	}



}
