/*******************************************************************************
 * File generated from the Project Management Ontology::projectmanagementontology::model::project_management_ontology::project_management_ontology::PlannedActivity uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 31 October 2024 16:51:36 CET
 *******************************************************************************/
package projectmanagementontology.model.project_management_ontology.project_management_ontology;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of PlannedActivity.
 * 
 * @author 
 */
public class PlannedActivity implements ActivityPhase {
	// Start of user code (user defined attributes for PlannedActivity)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public PlannedActivity() {
		// Start of user code constructor for PlannedActivity)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for PlannedActivity)
	
	// End of user code
	/**
	 * Returns activity.
	 * Originates from implemented interface.
	 * @return activity 
	 */
	@Override
	public Activity getActivity() {
		// Start of user code for method getActivity
		// TODO implement
		return null;
		// End of user code
	}
	
	


}
