/*******************************************************************************
 * File generated from the Project Management Ontology::projectmanagementontology::model::project_management_ontology::project_management_ontology::PlannedSchedule uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 31 October 2024 16:51:36 CET
 *******************************************************************************/
package projectmanagementontology.model.project_management_ontology.project_management_ontology;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of PlannedSchedule.
 * 
 * @author 
 */
public class PlannedSchedule {
	/**
	 * Description of the property project.
	 */
	public final Project project = null;
	
	// Start of user code (user defined attributes for PlannedSchedule)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public PlannedSchedule() {
		// Start of user code constructor for PlannedSchedule)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for PlannedSchedule)
	
	// End of user code
	
	
	/**
	 * Returns project.
	 * @return project 
	 */
	public Project getProject() {
		return this.project;
	}



}
