/*******************************************************************************
 * File generated from the Project Management Ontology::projectmanagementontology::model::project_management_ontology::project_management_ontology::Resource uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 31 October 2024 16:51:36 CET
 *******************************************************************************/
package projectmanagementontology.model.project_management_ontology.project_management_ontology;

import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Resource.
 * 
 * @author 
 */
public interface Resource {


	/**
	 * Returns resourceAllocation.
	 * @return resourceAllocation 
	 */
	ArrayList<ResourceAllocation> getResourceAllocation();
	
	
	/**
	 * Sets a value to attribute resourceAllocation. 
	 * @param newResourceAllocation 
	 */
	void setResourceAllocation(ArrayList<ResourceAllocation> newResourceAllocation);


	// Start of user code (user defined methods for Resource)
	
	// End of user code


}
