/*******************************************************************************
 * File generated from the Project Management Ontology::projectmanagementontology::model::project_management_ontology::project_management_ontology::ResourceAllocation uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 31 October 2024 16:51:36 CET
 *******************************************************************************/
package projectmanagementontology.model.project_management_ontology.project_management_ontology;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ResourceAllocation.
 * 
 * @author 
 */
public class ResourceAllocation {
	/**
	 * Description of the property performedActivity.
	 */
	public final PerformedActivity performedActivity = null;
	
	/**
	 * Description of the property resource.
	 */
	public final Resource resource = null;
	
	// Start of user code (user defined attributes for ResourceAllocation)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ResourceAllocation() {
		// Start of user code constructor for ResourceAllocation)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ResourceAllocation)
	
	// End of user code
	
	
	/**
	 * Returns performedActivity.
	 * @return performedActivity 
	 */
	public PerformedActivity getPerformedActivity() {
		return this.performedActivity;
	}

	/**
	 * Returns resource.
	 * @return resource 
	 */
	public Resource getResource() {
		return this.resource;
	}



}
