/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::Conta uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Conta.
 * 
 * @author 
 */
public class Conta {
	/**
	 * Description of the property contaEmSaqueRole.
	 */
	public ContaEmSaque contaEmSaqueRole = null;
	
	/**
	 * Description of the property contaEmDepsitoRole.
	 */
	public ContaEmDepsito contaEmDepsitoRole = null;
	
	// Start of user code (user defined attributes for Conta)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Conta() {
		// Start of user code constructor for Conta)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Conta)
	
	// End of user code
	
	
	/**
	 * Returns contaEmSaqueRole.
	 * @return contaEmSaqueRole 
	 */
	public ContaEmSaque getContaEmSaqueRole() {
		return this.contaEmSaqueRole;
	}
	
	/**
	 * Sets a value to attribute contaEmSaqueRole. 
	 * @param newContaEmSaqueRole 
	 */
	public void setContaEmSaqueRole(ContaEmSaque newContaEmSaqueRole) {
		this.contaEmSaqueRole = newContaEmSaqueRole;
	}

	/**
	 * Returns contaEmDepsitoRole.
	 * @return contaEmDepsitoRole 
	 */
	public ContaEmDepsito getContaEmDepsitoRole() {
		return this.contaEmDepsitoRole;
	}
	
	/**
	 * Sets a value to attribute contaEmDepsitoRole. 
	 * @param newContaEmDepsitoRole 
	 */
	public void setContaEmDepsitoRole(ContaEmDepsito newContaEmDepsitoRole) {
		this.contaEmDepsitoRole = newContaEmDepsitoRole;
	}



}
