/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::ContaEmSaque uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ContaEmSaque.
 * 
 * @author 
 */
public class ContaEmSaque {
	/**
	 * Description of the property saque.
	 */
	public Saque saque = null;
	
	/**
	 * Description of the property transferncia.
	 */
	public Transferncia transferncia = null;
	
	/**
	 * Description of the property conta.
	 */
	public final Conta conta = null;
	
	// Start of user code (user defined attributes for ContaEmSaque)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ContaEmSaque() {
		// Start of user code constructor for ContaEmSaque)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ContaEmSaque)
	
	// End of user code
	
	
	/**
	 * Returns saque.
	 * @return saque 
	 */
	public Saque getSaque() {
		return this.saque;
	}
	
	/**
	 * Sets a value to attribute saque. 
	 * @param newSaque 
	 */
	public void setSaque(Saque newSaque) {
		this.saque = newSaque;
	}

	/**
	 * Returns transferncia.
	 * @return transferncia 
	 */
	public Transferncia getTransferncia() {
		return this.transferncia;
	}
	
	/**
	 * Sets a value to attribute transferncia. 
	 * @param newTransferncia 
	 */
	public void setTransferncia(Transferncia newTransferncia) {
		this.transferncia = newTransferncia;
	}

	/**
	 * Returns conta.
	 * @return conta 
	 */
	public Conta getConta() {
		return this.conta;
	}



}
