/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::ContaPoupana uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ContaPoupana.
 * 
 * @author 
 */
public class ContaPoupana extends Conta {
	// Start of user code (user defined attributes for ContaPoupana)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ContaPoupana() {
		// Start of user code constructor for ContaPoupana)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ContaPoupana)
	
	// End of user code
	
	


}
