/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::ContaEmDepsito uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ContaEmDepsito.
 * 
 * @author 
 */
public class ContaEmDepsito {
	/**
	 * Description of the property transferncia.
	 */
	public Transferncia transferncia = null;
	
	/**
	 * Description of the property conta.
	 */
	public final Conta conta = null;
	
	/**
	 * Description of the property depsito.
	 */
	public Depsito depsito = null;
	
	// Start of user code (user defined attributes for ContaEmDepsito)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ContaEmDepsito() {
		// Start of user code constructor for ContaEmDepsito)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ContaEmDepsito)
	
	// End of user code
	
	
	/**
	 * Returns transferncia.
	 * @return transferncia 
	 */
	public Transferncia getTransferncia() {
		return this.transferncia;
	}
	
	/**
	 * Sets a value to attribute transferncia. 
	 * @param newTransferncia 
	 */
	public void setTransferncia(Transferncia newTransferncia) {
		this.transferncia = newTransferncia;
	}

	/**
	 * Returns conta.
	 * @return conta 
	 */
	public Conta getConta() {
		return this.conta;
	}

	/**
	 * Returns depsito.
	 * @return depsito 
	 */
	public Depsito getDepsito() {
		return this.depsito;
	}
	
	/**
	 * Sets a value to attribute depsito. 
	 * @param newDepsito 
	 */
	public void setDepsito(Depsito newDepsito) {
		this.depsito = newDepsito;
	}



}
