/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::Depsito uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Depsito.
 * 
 * @author 
 */
public class Depsito {
	/**
	 * Description of the property contaEmDepsito.
	 */
	public final ContaEmDepsito contaEmDepsito = null;
	
	// Start of user code (user defined attributes for Depsito)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Depsito() {
		// Start of user code constructor for Depsito)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Depsito)
	
	// End of user code
	
	
	/**
	 * Returns contaEmDepsito.
	 * @return contaEmDepsito 
	 */
	public ContaEmDepsito getContaEmDepsito() {
		return this.contaEmDepsito;
	}



}
