/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::FuncionrioCaixaEmOperao uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of FuncionrioCaixaEmOperao.
 * 
 * @author 
 */
public class FuncionrioCaixaEmOperao {
	/**
	 * Description of the property op_func.
	 */
	public ArrayList<Operao> op_func = new ArrayList<Operao>();
	
	/**
	 * Description of the property funcionrioCaixa.
	 */
	public final FuncionrioCaixa funcionrioCaixa = null;
	
	/**
	 * Description of the property recibo.
	 */
	public ArrayList<Recibo> recibo = new ArrayList<Recibo>();
	
	// Start of user code (user defined attributes for FuncionrioCaixaEmOperao)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public FuncionrioCaixaEmOperao() {
		// Start of user code constructor for FuncionrioCaixaEmOperao)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for FuncionrioCaixaEmOperao)
	
	// End of user code
	
	
	/**
	 * Returns op_func.
	 * @return op_func 
	 */
	public ArrayList<Operao> getOp_func() {
		return this.op_func;
	}
	
	/**
	 * Sets a value to attribute op_func. 
	 * @param newOp_func 
	 */
	public void setOp_func(ArrayList<Operao> newOp_func) {
	    this.op_func = newOp_func;
	}
	
	/**
	 * Adds one attribute (if op_func had a multiple cardinality)
	 * @param operaoToAdd in op_func
	 */
	public void addOperaoToOp_func(Operao operaoToAdd) {
		this.op_func.add(operaoToAdd);
	}
	
	/**
	 * Removes an attribute (if op_func had a multiple cardinality)
	 * @param operaoToRemove in op_func
	 */
	public void removeOperaoToOp_func(Operao operaoToRemove) {
		this.op_func.remove(operaoToRemove);
	}
	
	/**
	 * Adds all the attribute (if op_func had a multiple cardinality)
	 * @param operaosToAdd in op_func
	 */
	public void addAllOperaoToOp_func(ArrayList<Operao> operaosToAdd) {
		this.op_func.addAll(operaosToAdd);
	}
	
	/**
	 * Removes all the attribute (if op_func had a multiple cardinality)
	 * @param operaosToRemove in op_func
	 */
	public void removeAllOperaoToOp_func(ArrayList<Operao> operaosToRemove) {
		this.op_func.removeAll(operaosToRemove);
	}

	/**
	 * Returns funcionrioCaixa.
	 * @return funcionrioCaixa 
	 */
	public FuncionrioCaixa getFuncionrioCaixa() {
		return this.funcionrioCaixa;
	}

	/**
	 * Returns recibo.
	 * @return recibo 
	 */
	public ArrayList<Recibo> getRecibo() {
		return this.recibo;
	}
	
	/**
	 * Sets a value to attribute recibo. 
	 * @param newRecibo 
	 */
	public void setRecibo(ArrayList<Recibo> newRecibo) {
	    this.recibo = newRecibo;
	}
	
	/**
	 * Adds one attribute (if recibo had a multiple cardinality)
	 * @param reciboToAdd in recibo
	 */
	public void addReciboToRecibo(Recibo reciboToAdd) {
		this.recibo.add(reciboToAdd);
	}
	
	/**
	 * Removes an attribute (if recibo had a multiple cardinality)
	 * @param reciboToRemove in recibo
	 */
	public void removeReciboToRecibo(Recibo reciboToRemove) {
		this.recibo.remove(reciboToRemove);
	}
	
	/**
	 * Adds all the attribute (if recibo had a multiple cardinality)
	 * @param recibosToAdd in recibo
	 */
	public void addAllReciboToRecibo(ArrayList<Recibo> recibosToAdd) {
		this.recibo.addAll(recibosToAdd);
	}
	
	/**
	 * Removes all the attribute (if recibo had a multiple cardinality)
	 * @param recibosToRemove in recibo
	 */
	public void removeAllReciboToRecibo(ArrayList<Recibo> recibosToRemove) {
		this.recibo.removeAll(recibosToRemove);
	}



}
