/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::FuncionrioCaixa uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of FuncionrioCaixa.
 * 
 * @author 
 */
public class FuncionrioCaixa {
	/**
	 * Description of the property funcionrioCaixaEmOperaoRole.
	 */
	public FuncionrioCaixaEmOperao funcionrioCaixaEmOperaoRole = null;
	
	/**
	 * Description of the property pessoaComConta.
	 */
	public final PessoaComConta pessoaComConta = null;
	
	// Start of user code (user defined attributes for FuncionrioCaixa)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public FuncionrioCaixa() {
		// Start of user code constructor for FuncionrioCaixa)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for FuncionrioCaixa)
	
	// End of user code
	
	
	/**
	 * Returns funcionrioCaixaEmOperaoRole.
	 * @return funcionrioCaixaEmOperaoRole 
	 */
	public FuncionrioCaixaEmOperao getFuncionrioCaixaEmOperaoRole() {
		return this.funcionrioCaixaEmOperaoRole;
	}
	
	/**
	 * Sets a value to attribute funcionrioCaixaEmOperaoRole. 
	 * @param newFuncionrioCaixaEmOperaoRole 
	 */
	public void setFuncionrioCaixaEmOperaoRole(FuncionrioCaixaEmOperao newFuncionrioCaixaEmOperaoRole) {
		this.funcionrioCaixaEmOperaoRole = newFuncionrioCaixaEmOperaoRole;
	}

	/**
	 * Returns pessoaComConta.
	 * @return pessoaComConta 
	 */
	public PessoaComConta getPessoaComConta() {
		return this.pessoaComConta;
	}



}
