/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::Operao uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Operao.
 * 
 * @author 
 */
public class Operao {
	/**
	 * Description of the property recibo.
	 */
	public Recibo recibo = null;
	
	/**
	 * Description of the property cliente.
	 */
	public final Cliente cliente = null;
	
	/**
	 * Description of the property funcionrioCaixaEmOperao.
	 */
	public final FuncionrioCaixaEmOperao funcionrioCaixaEmOperao = null;
	
	// Start of user code (user defined attributes for Operao)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Operao() {
		// Start of user code constructor for Operao)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Operao)
	
	// End of user code
	
	
	/**
	 * Returns recibo.
	 * @return recibo 
	 */
	public Recibo getRecibo() {
		return this.recibo;
	}
	
	/**
	 * Sets a value to attribute recibo. 
	 * @param newRecibo 
	 */
	public void setRecibo(Recibo newRecibo) {
		this.recibo = newRecibo;
	}

	/**
	 * Returns cliente.
	 * @return cliente 
	 */
	public Cliente getCliente() {
		return this.cliente;
	}

	/**
	 * Returns funcionrioCaixaEmOperao.
	 * @return funcionrioCaixaEmOperao 
	 */
	public FuncionrioCaixaEmOperao getFuncionrioCaixaEmOperao() {
		return this.funcionrioCaixaEmOperao;
	}



}
