/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::PessoaComConta uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of PessoaComConta.
 * 
 * @author 
 */
public class PessoaComConta {
	/**
	 * Description of the property saqueEmDinheiro.
	 */
	public SaqueEmDinheiro saqueEmDinheiro = null;
	
	/**
	 * Description of the property funcionrioCaixaRole.
	 */
	public FuncionrioCaixa funcionrioCaixaRole = null;
	
	/**
	 * Description of the property pessoa.
	 */
	public final Pessoa pessoa = null;
	
	// Start of user code (user defined attributes for PessoaComConta)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public PessoaComConta() {
		// Start of user code constructor for PessoaComConta)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for PessoaComConta)
	
	// End of user code
	
	
	/**
	 * Returns saqueEmDinheiro.
	 * @return saqueEmDinheiro 
	 */
	public SaqueEmDinheiro getSaqueEmDinheiro() {
		return this.saqueEmDinheiro;
	}
	
	/**
	 * Sets a value to attribute saqueEmDinheiro. 
	 * @param newSaqueEmDinheiro 
	 */
	public void setSaqueEmDinheiro(SaqueEmDinheiro newSaqueEmDinheiro) {
		this.saqueEmDinheiro = newSaqueEmDinheiro;
	}

	/**
	 * Returns funcionrioCaixaRole.
	 * @return funcionrioCaixaRole 
	 */
	public FuncionrioCaixa getFuncionrioCaixaRole() {
		return this.funcionrioCaixaRole;
	}
	
	/**
	 * Sets a value to attribute funcionrioCaixaRole. 
	 * @param newFuncionrioCaixaRole 
	 */
	public void setFuncionrioCaixaRole(FuncionrioCaixa newFuncionrioCaixaRole) {
		this.funcionrioCaixaRole = newFuncionrioCaixaRole;
	}

	/**
	 * Returns pessoa.
	 * @return pessoa 
	 */
	public Pessoa getPessoa() {
		return this.pessoa;
	}



}
