/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::Recibo uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Recibo.
 * 
 * @author 
 */
public class Recibo {
	/**
	 * Description of the property funcionrioCaixaEmOperao.
	 */
	public final FuncionrioCaixaEmOperao funcionrioCaixaEmOperao = null;
	
	/**
	 * Description of the property operao.
	 */
	public final Operao operao = null;
	
	/**
	 * Description of the property cliente.
	 */
	public final Cliente cliente = null;
	
	// Start of user code (user defined attributes for Recibo)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Recibo() {
		// Start of user code constructor for Recibo)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Recibo)
	
	// End of user code
	
	
	/**
	 * Returns funcionrioCaixaEmOperao.
	 * @return funcionrioCaixaEmOperao 
	 */
	public FuncionrioCaixaEmOperao getFuncionrioCaixaEmOperao() {
		return this.funcionrioCaixaEmOperao;
	}

	/**
	 * Returns operao.
	 * @return operao 
	 */
	public Operao getOperao() {
		return this.operao;
	}

	/**
	 * Returns cliente.
	 * @return cliente 
	 */
	public Cliente getCliente() {
		return this.cliente;
	}



}
