/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::Saque uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Saque.
 * 
 * @author 
 */
public class Saque {
	/**
	 * Description of the property contaEmSaque.
	 */
	public final ContaEmSaque contaEmSaque = null;
	
	// Start of user code (user defined attributes for Saque)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Saque() {
		// Start of user code constructor for Saque)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Saque)
	
	// End of user code
	
	
	/**
	 * Returns contaEmSaque.
	 * @return contaEmSaque 
	 */
	public ContaEmSaque getContaEmSaque() {
		return this.contaEmSaque;
	}



}
