/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::SaqueEmTransferncia uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of SaqueEmTransferncia.
 * 
 * @author 
 */
public class SaqueEmTransferncia {
	/**
	 * Description of the property transferncia.
	 */
	public Transferncia transferncia = null;
	
	// Start of user code (user defined attributes for SaqueEmTransferncia)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public SaqueEmTransferncia() {
		// Start of user code constructor for SaqueEmTransferncia)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for SaqueEmTransferncia)
	
	// End of user code
	
	
	/**
	 * Returns transferncia.
	 * @return transferncia 
	 */
	public Transferncia getTransferncia() {
		return this.transferncia;
	}
	
	/**
	 * Sets a value to attribute transferncia. 
	 * @param newTransferncia 
	 */
	public void setTransferncia(Transferncia newTransferncia) {
		this.transferncia = newTransferncia;
	}



}
