/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::SaqueEmDinheiro uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of SaqueEmDinheiro.
 * 
 * @author 
 */
public class SaqueEmDinheiro {
	/**
	 * Description of the property pessoaComConta.
	 */
	public final PessoaComConta pessoaComConta = null;
	
	// Start of user code (user defined attributes for SaqueEmDinheiro)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public SaqueEmDinheiro() {
		// Start of user code constructor for SaqueEmDinheiro)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for SaqueEmDinheiro)
	
	// End of user code
	
	
	/**
	 * Returns pessoaComConta.
	 * @return pessoaComConta 
	 */
	public PessoaComConta getPessoaComConta() {
		return this.pessoaComConta;
	}



}
