/*******************************************************************************
 * File generated from the LucasBassetti_CaixaBanco::bankaccount2013::model::lucasbassetti_caixabanco::caixa_banco::Transferncia uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:23:12 CEST
 *******************************************************************************/
package bankaccount2013.model.lucasbassetti_caixabanco.caixa_banco;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Transferncia.
 * 
 * @author 
 */
public class Transferncia {
	/**
	 * Description of the property saqueEmTransferncia.
	 */
	public final SaqueEmTransferncia saqueEmTransferncia = null;
	
	/**
	 * Description of the property contaEmSaque.
	 */
	public final ContaEmSaque contaEmSaque = null;
	
	/**
	 * Description of the property contaEmDepsito.
	 */
	public final ContaEmDepsito contaEmDepsito = null;
	
	// Start of user code (user defined attributes for Transferncia)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Transferncia() {
		// Start of user code constructor for Transferncia)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Transferncia)
	
	// End of user code
	
	
	/**
	 * Returns saqueEmTransferncia.
	 * @return saqueEmTransferncia 
	 */
	public SaqueEmTransferncia getSaqueEmTransferncia() {
		return this.saqueEmTransferncia;
	}

	/**
	 * Returns contaEmSaque.
	 * @return contaEmSaque 
	 */
	public ContaEmSaque getContaEmSaque() {
		return this.contaEmSaque;
	}

	/**
	 * Returns contaEmDepsito.
	 * @return contaEmDepsito 
	 */
	public ContaEmDepsito getContaEmDepsito() {
		return this.contaEmDepsito;
	}



}
