/*******************************************************************************
 * File generated from the barros2020programming::barros2020programming::model::barros2020programming::ARequerimentoart12IcSegundaParte uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:24:07 CEST
 *******************************************************************************/
package barros2020programming.model.barros2020programming;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ARequerimentoart12IcSegundaParte.
 * 
 * @author 
 */
public class ARequerimentoart12IcSegundaParte extends JusSanguinis {
	// Start of user code (user defined attributes for ARequerimentoart12IcSegundaParte)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ARequerimentoart12IcSegundaParte() {
		// Start of user code constructor for ARequerimentoart12IcSegundaParte)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ARequerimentoart12IcSegundaParte)
	
	// End of user code
	
	


}
