/*******************************************************************************
 * File generated from the barros2020programming::barros2020programming::model::barros2020programming::Definitivaart12Ib uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:24:07 CEST
 *******************************************************************************/
package barros2020programming.model.barros2020programming;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Definitivaart12Ib.
 * 
 * @author 
 */
public class Definitivaart12Ib extends JusSanguinis {
	// Start of user code (user defined attributes for Definitivaart12Ib)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Definitivaart12Ib() {
		// Start of user code constructor for Definitivaart12Ib)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Definitivaart12Ib)
	
	// End of user code
	
	


}
