/*******************************************************************************
 * File generated from the barros2020programming::barros2020programming::model::barros2020programming::EstrangeirosDeQualquerNacionalidade uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:24:07 CEST
 *******************************************************************************/
package barros2020programming.model.barros2020programming;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of EstrangeirosDeQualquerNacionalidade.
 * 
 * @author 
 */
public class EstrangeirosDeQualquerNacionalidade extends NacionalidadeBrasileiraNaturalizada {
	// Start of user code (user defined attributes for EstrangeirosDeQualquerNacionalidade)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public EstrangeirosDeQualquerNacionalidade() {
		// Start of user code constructor for EstrangeirosDeQualquerNacionalidade)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for EstrangeirosDeQualquerNacionalidade)
	
	// End of user code
	
	


}
