/*******************************************************************************
 * File generated from the barros2020programming::barros2020programming::model::barros2020programming::JusSolisart12Ia uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:24:07 CEST
 *******************************************************************************/
package barros2020programming.model.barros2020programming;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of JusSolisart12Ia.
 * 
 * @author 
 */
public class JusSolisart12Ia extends NacionalidadeBrasileiraNata {
	// Start of user code (user defined attributes for JusSolisart12Ia)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public JusSolisart12Ia() {
		// Start of user code constructor for JusSolisart12Ia)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for JusSolisart12Ia)
	
	// End of user code
	
	


}
