/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::spo::Artifact uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:43 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.spo;

import aguiar2018rdbso.model.ontology.rdbso.Language;
import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of Artifact.
 * 
 * @author 
 */
public interface Artifact {


	/**
	 * Returns language.
	 * @return language 
	 */
	ArrayList<Language> getLanguage();
	
	
	/**
	 * Sets a value to attribute language. 
	 * @param newLanguage 
	 */
	void setLanguage(ArrayList<Language> newLanguage);


	// Start of user code (user defined methods for Artifact)
	
	// End of user code


}
