/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::spo::SoftwareItem uml Interface
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:43 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.spo;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of SoftwareItem.
 * 
 * @author 
 */
public interface SoftwareItem  extends Artifact{



	// Start of user code (user defined methods for SoftwareItem)
	
	// End of user code


}
