/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::rdbso::DataTypeConstraint uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:43 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.rdbso;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of DataTypeConstraint.
 * 
 * @author 
 */
public class DataTypeConstraint extends Constraint {
	/**
	 * Description of the property dataType.
	 */
	public DataType dataType = null;
	
	// Start of user code (user defined attributes for DataTypeConstraint)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public DataTypeConstraint() {
		// Start of user code constructor for DataTypeConstraint)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for DataTypeConstraint)
	
	// End of user code
	
	
	/**
	 * Returns dataType.
	 * @return dataType 
	 */
	public DataType getDataType() {
		return this.dataType;
	}
	
	/**
	 * Sets a value to attribute dataType. 
	 * @param newDataType 
	 */
	public void setDataType(DataType newDataType) {
		this.dataType = newDataType;
	}



}
