/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::rdbso::ExternalDataType uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:42 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.rdbso;

import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of ExternalDataType.
 * 
 * @author 
 */
public class ExternalDataType extends DataType {
	/**
	 * Description of the property dataType.
	 */
	public ArrayList<DataType> dataType = new ArrayList<DataType>();
	
	// Start of user code (user defined attributes for ExternalDataType)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ExternalDataType() {
		// Start of user code constructor for ExternalDataType)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ExternalDataType)
	
	// End of user code
	
	
	/**
	 * Returns dataType.
	 * @return dataType 
	 */
	public ArrayList<DataType> getDataType() {
		return this.dataType;
	}
	
	/**
	 * Sets a value to attribute dataType. 
	 * @param newDataType 
	 */
	public void setDataType(ArrayList<DataType> newDataType) {
	    this.dataType = newDataType;
	}
	
	/**
	 * Adds one attribute (if dataType had a multiple cardinality)
	 * @param dataTypeToAdd in dataType
	 */
	public void addDataTypeToDataType(DataType dataTypeToAdd) {
		this.dataType.add(dataTypeToAdd);
	}
	
	/**
	 * Removes an attribute (if dataType had a multiple cardinality)
	 * @param dataTypeToRemove in dataType
	 */
	public void removeDataTypeToDataType(DataType dataTypeToRemove) {
		this.dataType.remove(dataTypeToRemove);
	}
	
	/**
	 * Adds all the attribute (if dataType had a multiple cardinality)
	 * @param dataTypesToAdd in dataType
	 */
	public void addAllDataTypeToDataType(ArrayList<DataType> dataTypesToAdd) {
		this.dataType.addAll(dataTypesToAdd);
	}
	
	/**
	 * Removes all the attribute (if dataType had a multiple cardinality)
	 * @param dataTypesToRemove in dataType
	 */
	public void removeAllDataTypeToDataType(ArrayList<DataType> dataTypesToRemove) {
		this.dataType.removeAll(dataTypesToRemove);
	}



}
