/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::rdbso::ForeignKeyColumn uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:42 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.rdbso;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of ForeignKeyColumn.
 * 
 * @author 
 */
public class ForeignKeyColumn {
	/**
	 * Description of the property column.
	 */
	public final Column column = null;
	
	// Start of user code (user defined attributes for ForeignKeyColumn)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ForeignKeyColumn() {
		// Start of user code constructor for ForeignKeyColumn)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ForeignKeyColumn)
	
	// End of user code
	
	
	/**
	 * Returns column.
	 * @return column 
	 */
	public Column getColumn() {
		return this.column;
	}



}
