/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::rdbso::InternalDataType uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:42 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.rdbso;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of InternalDataType.
 * 
 * @author 
 */
public class InternalDataType extends DataType {
	// Start of user code (user defined attributes for InternalDataType)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public InternalDataType() {
		// Start of user code constructor for InternalDataType)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for InternalDataType)
	
	// End of user code
	
	


}
