/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::rdbso::Line uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:43 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.rdbso;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of Line.
 * 
 * @author 
 */
public class Line {
	/**
	 * Description of the property lineType.
	 */
	public LineType lineType = null;
	
	// Start of user code (user defined attributes for Line)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public Line() {
		// Start of user code constructor for Line)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for Line)
	
	// End of user code
	
	
	/**
	 * Returns lineType.
	 * @return lineType 
	 */
	public LineType getLineType() {
		return this.lineType;
	}
	
	/**
	 * Sets a value to attribute lineType. 
	 * @param newLineType 
	 */
	public void setLineType(LineType newLineType) {
		this.lineType = newLineType;
	}



}
