/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::rdbso::PrimaryKeyConstraint uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:43 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.rdbso;

// Start of user code (user defined imports)

// End of user code

/**
 * Description of PrimaryKeyConstraint.
 * 
 * @author 
 */
public class PrimaryKeyConstraint extends ColumnConstraint {
	// Start of user code (user defined attributes for PrimaryKeyConstraint)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public PrimaryKeyConstraint() {
		// Start of user code constructor for PrimaryKeyConstraint)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for PrimaryKeyConstraint)
	
	// End of user code
	
	


}
