/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::swo::ComputerSystem uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:43 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.swo;

import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of ComputerSystem.
 * 
 * @author 
 */
public class ComputerSystem {
	/**
	 * Description of the property loadedSoftwareSystemCopy.
	 */
	public ArrayList<LoadedSoftwareSystemCopy> loadedSoftwareSystemCopy = new ArrayList<LoadedSoftwareSystemCopy>();
	
	// Start of user code (user defined attributes for ComputerSystem)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public ComputerSystem() {
		// Start of user code constructor for ComputerSystem)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for ComputerSystem)
	
	// End of user code
	
	
	/**
	 * Returns loadedSoftwareSystemCopy.
	 * @return loadedSoftwareSystemCopy 
	 */
	public ArrayList<LoadedSoftwareSystemCopy> getLoadedSoftwareSystemCopy() {
		return this.loadedSoftwareSystemCopy;
	}
	
	/**
	 * Sets a value to attribute loadedSoftwareSystemCopy. 
	 * @param newLoadedSoftwareSystemCopy 
	 */
	public void setLoadedSoftwareSystemCopy(ArrayList<LoadedSoftwareSystemCopy> newLoadedSoftwareSystemCopy) {
	    this.loadedSoftwareSystemCopy = newLoadedSoftwareSystemCopy;
	}
	
	/**
	 * Adds one attribute (if loadedSoftwareSystemCopy had a multiple cardinality)
	 * @param loadedSoftwareSystemCopyToAdd in loadedSoftwareSystemCopy
	 */
	public void addLoadedSoftwareSystemCopyToLoadedSoftwareSystemCopy(LoadedSoftwareSystemCopy loadedSoftwareSystemCopyToAdd) {
		this.loadedSoftwareSystemCopy.add(loadedSoftwareSystemCopyToAdd);
	}
	
	/**
	 * Removes an attribute (if loadedSoftwareSystemCopy had a multiple cardinality)
	 * @param loadedSoftwareSystemCopyToRemove in loadedSoftwareSystemCopy
	 */
	public void removeLoadedSoftwareSystemCopyToLoadedSoftwareSystemCopy(LoadedSoftwareSystemCopy loadedSoftwareSystemCopyToRemove) {
		this.loadedSoftwareSystemCopy.remove(loadedSoftwareSystemCopyToRemove);
	}
	
	/**
	 * Adds all the attribute (if loadedSoftwareSystemCopy had a multiple cardinality)
	 * @param loadedSoftwareSystemCopysToAdd in loadedSoftwareSystemCopy
	 */
	public void addAllLoadedSoftwareSystemCopyToLoadedSoftwareSystemCopy(ArrayList<LoadedSoftwareSystemCopy> loadedSoftwareSystemCopysToAdd) {
		this.loadedSoftwareSystemCopy.addAll(loadedSoftwareSystemCopysToAdd);
	}
	
	/**
	 * Removes all the attribute (if loadedSoftwareSystemCopy had a multiple cardinality)
	 * @param loadedSoftwareSystemCopysToRemove in loadedSoftwareSystemCopy
	 */
	public void removeAllLoadedSoftwareSystemCopyToLoadedSoftwareSystemCopy(ArrayList<LoadedSoftwareSystemCopy> loadedSoftwareSystemCopysToRemove) {
		this.loadedSoftwareSystemCopy.removeAll(loadedSoftwareSystemCopysToRemove);
	}



}
