/*******************************************************************************
 * File generated from the ontology::aguiar2018rdbso::model::ontology::swo::SoftwareSystem uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 * Date: 19 October 2024 20:22:43 CEST
 *******************************************************************************/
package aguiar2018rdbso.model.ontology.swo;

import aguiar2018rdbso.model.ontology.rdbso.Language;
import aguiar2018rdbso.model.ontology.spo.Artifact;
import aguiar2018rdbso.model.ontology.spo.SoftwareItem;
import java.util.ArrayList;
// Start of user code (user defined imports)

// End of user code

/**
 * Description of SoftwareSystem.
 * 
 * @author 
 */
public class SoftwareSystem implements SoftwareItem {
	/**
	 * Description of the property loadedSoftwareSystemCopy.
	 */
	public ArrayList<LoadedSoftwareSystemCopy> loadedSoftwareSystemCopy = new ArrayList<LoadedSoftwareSystemCopy>();
	
	// Start of user code (user defined attributes for SoftwareSystem)
	
	// End of user code
	
	/**
	 * The constructor.
	 */
	public SoftwareSystem() {
		// Start of user code constructor for SoftwareSystem)
		super();
		// End of user code
	}
	
	// Start of user code (user defined methods for SoftwareSystem)
	
	// End of user code
	/**
	 * Returns language.
	 * Originates from implemented interface.
	 * @return language 
	 */
	@Override
	public ArrayList<Language> getLanguage() {
		// Start of user code for method getLanguage
		// TODO implement
		return new ArrayList<Language>();
		// End of user code
	}
	
	/**
	 * Sets a value to attribute language. 
	 * Originates from implemented interface.
	 * @param newLanguage 
	 */
	@Override
	public void setLanguage(ArrayList<Language> newLanguage) {
		// Start of user code for method setLanguage
		// TODO implement
		// End of user code
	}
	
	
	/**
	 * Returns loadedSoftwareSystemCopy.
	 * @return loadedSoftwareSystemCopy 
	 */
	public ArrayList<LoadedSoftwareSystemCopy> getLoadedSoftwareSystemCopy() {
		return this.loadedSoftwareSystemCopy;
	}
	
	/**
	 * Sets a value to attribute loadedSoftwareSystemCopy. 
	 * @param newLoadedSoftwareSystemCopy 
	 */
	public void setLoadedSoftwareSystemCopy(ArrayList<LoadedSoftwareSystemCopy> newLoadedSoftwareSystemCopy) {
	    this.loadedSoftwareSystemCopy = newLoadedSoftwareSystemCopy;
	}
	
	/**
	 * Adds one attribute (if loadedSoftwareSystemCopy had a multiple cardinality)
	 * @param loadedSoftwareSystemCopyToAdd in loadedSoftwareSystemCopy
	 */
	public void addLoadedSoftwareSystemCopyToLoadedSoftwareSystemCopy(LoadedSoftwareSystemCopy loadedSoftwareSystemCopyToAdd) {
		this.loadedSoftwareSystemCopy.add(loadedSoftwareSystemCopyToAdd);
	}
	
	/**
	 * Removes an attribute (if loadedSoftwareSystemCopy had a multiple cardinality)
	 * @param loadedSoftwareSystemCopyToRemove in loadedSoftwareSystemCopy
	 */
	public void removeLoadedSoftwareSystemCopyToLoadedSoftwareSystemCopy(LoadedSoftwareSystemCopy loadedSoftwareSystemCopyToRemove) {
		this.loadedSoftwareSystemCopy.remove(loadedSoftwareSystemCopyToRemove);
	}
	
	/**
	 * Adds all the attribute (if loadedSoftwareSystemCopy had a multiple cardinality)
	 * @param loadedSoftwareSystemCopysToAdd in loadedSoftwareSystemCopy
	 */
	public void addAllLoadedSoftwareSystemCopyToLoadedSoftwareSystemCopy(ArrayList<LoadedSoftwareSystemCopy> loadedSoftwareSystemCopysToAdd) {
		this.loadedSoftwareSystemCopy.addAll(loadedSoftwareSystemCopysToAdd);
	}
	
	/**
	 * Removes all the attribute (if loadedSoftwareSystemCopy had a multiple cardinality)
	 * @param loadedSoftwareSystemCopysToRemove in loadedSoftwareSystemCopy
	 */
	public void removeAllLoadedSoftwareSystemCopyToLoadedSoftwareSystemCopy(ArrayList<LoadedSoftwareSystemCopy> loadedSoftwareSystemCopysToRemove) {
		this.loadedSoftwareSystemCopy.removeAll(loadedSoftwareSystemCopysToRemove);
	}



}
